#pragma once

#include <WinUser.h>

#define UDM_SEM_EDIT_CLICK							(WM_USER+100)

//RX
#define UDM_SEM_RX_DATA_INTERFACE_CLICK				(WM_USER+101)
#define UDM_SEM_LIMIT_AMP_ENABLE_CLICK				(WM_USER+102)
#define UDM_SEM_LNA_GAIN_CLICK						(WM_USER+103)

//TX
#define UDM_SEM_DUTY_CYCLE_CLICK					(WM_USER+110)
#define UDM_SEM_VCO_OSC_FREQ_CLICK					(WM_USER+111)
#define UDM_SEM_REG_REF_VOLT_CLICK					(WM_USER+112)
#define UDM_SEM_VCO_VDD_CLICK						(WM_USER+113)
#define UDM_SEM_VCO_POWER_CLICK						(WM_USER+114)
#define UDM_SEM_MODULATOR_POWER_CLICK				(WM_USER+115)
#define UDM_SEM_TEST_BUFFER_POWER_CLICK				(WM_USER+116)
#define UDM_SEM_DATA_INPUT_SELECT_CLICK				(WM_USER+117)
#define UDM_SEM_PA_POWER_CLICK						(WM_USER+118)
#define UDM_SEM_PA_GAIN_CONTROL1					(WM_USER+119)
#define UDM_SEM_PA_GAIN_CONTROL2					(WM_USER+120)
#define UDM_SEM_TEST_BUFFER_CURRENT_CLICK			(WM_USER+121)

//BIAS
#define UDM_SEM_BIAS_BLOCK_ENABLE_CLICK				(WM_USER+130)
#define UDM_SEM_1ST_STAGE_BIAS_CURRENT_CLICK		(WM_USER+131)
#define UDM_SEM_2ND_STAGE_BIAS_CURRENT_CLICK		(WM_USER+132)
#define UDM_SEM_3RD_STAGE_BIAS_CURRENT_CLICK		(WM_USER+133)
#define UDM_SEM_4TH_STAGE_BIAS_CURRENT_CLICK		(WM_USER+134)
#define UDM_SEM_5TH_STAGE_BIAS_CURRENT_CLICK		(WM_USER+135)
#define UDM_SEM_REF_STAGE_CURRENT_CLICK				(WM_USER+136)
#define UDM_SEM_IP_STAGE_CURRENT_CLICK				(WM_USER+137)
#define UDM_SEM_FB_CURRENT_CLICK					(WM_USER+138)
#define UDM_SEM_CORE_CURRENT_CLICK					(WM_USER+139)
#define UDM_SEM_OP_BUFFER_CURRENT_CLICK				(WM_USER+140)
#define UDM_SEM_IP_BUFFER_CURRENT_CLICK				(WM_USER+141)
#define UDM_SEM_HIGHLOW_DATA_RATE_CURRENT_CLICK		(WM_USER+142)
#define UDM_SEM_CMOS_GAIN_STAGE_CURRENT_CLICK		(WM_USER+143)
#define UDM_SEM_CML_INTERFACE_STAGE_CURRENT_CLICK	(WM_USER+144)
